name: yahtzee-hs
version: 0.1.0
license: MIT


dependencies:
  - base >=4.14 && <5
  - aeson >=2.0
  - async >=2.2
  - bytestring >=0.10
  - containers >=0.6
  - network >=3.1
  - stm >=2.5
  - text >=1.2
  - vector >=0.12
  - random >=1.2
  - time >=1.9
  - process >=1.6
  - threepenny-gui >=0.9


library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DeriveAnyClass
    - RecordWildCards
    - LambdaCase
    - NamedFieldPuns

executables:
  # Server
  yahtzee-server:
    source-dirs: app
    main: Server.hs
    other-modules: []
    # Chỉ định module Server là nơi chứa hàm main
    ghc-options: -main-is Server
    dependencies:
      - yahtzee-hs

  # Client CLI
  yahtzee-client:
    source-dirs: app
    main: Client.hs
    other-modules: []
    # Chỉ định module Client là nơi chứa hàm main
    ghc-options: -main-is Client
    dependencies:
      - yahtzee-hs

  # Client TUI (GUI)
  yahtzee-tui-client:
    source-dirs: app
    main: Main.hs
    other-modules: [Client]
    # Module chính của TUI là Main.hs (module Main), không cần ghc-options
    dependencies:
      - yahtzee-hs
      - threepenny-gui